api_platform:
    title: Grabniolec API
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/Session/Infrastructure/ApiPlatform/Resource'
            - '%kernel.project_dir%/src/Spotify/Infrastructure/ApiPlatform/Resource'
            - '%kernel.project_dir%/src/Lyrics/Infrastructure/ApiPlatform/Resource'
            - '%kernel.project_dir%/src/Vote/Infrastructure/ApiPlatform/Resource'
    formats:
        jsonld: ['application/ld+json', 'application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    exception_to_status:
        Webmozart\Assert\InvalidArgumentException: 400
        App\Spotify\Domain\Exception\XStateHeaderRequiredException: 400
        App\Spotify\Domain\Exception\UnauthorizedException: 401
